const AdminPageTableStyles = {
    tableContainer: {
      width: "100%",
      maxHeight: "240px",
      overflowY: "auto",
      backgroundColor: "#FFFFFF",
      borderRadius: "5px",
      border: "1px solid #F4F4F4",
      marginTop: "20px",
    },
    tableHead: {
      position: "sticky",
      top: "0px",
      width: "1193px",
      height: "41px",
      zIndex: 2,
      //padding: "12px 15px",
      gap: "100px",
      borderRadius: "0px 0px 0px 0px",
      background: "#111827",
      color: "white",
      textAlign: "center"
    },
    bodyCell: {
      fontFamily: "Inter",
      fontSize: "14px",
      fontWeight: 400,
      lineHeight: "16.94px",
      color: "#5F5F5F",
      padding: "12px 15px",
      textAlign: "center",
    },
    rowStyle: (index) => ({
      backgroundColor: index % 2 === 0 ? "#EAFEFF" : "#FFFFFF",
      borderBottom: "1px solid #F4F4F4",
    }),

      roomNameSelect: {
          width: "131px",
          height: "32px",
          top: "2.5px",
          //left: "342px",
          borderRadius: "4px",
          padding: "7px 10px",
          gap: "10px",
          border: "1px solid #8888883D",
          background: "#FFFFFF",
          color: "#1E1E1E",
      },
      menuItemText: {
          width: "81px",
          height: "17px",
          fontFamily: "Inter",
          fontWeight: 500,
          fontSize: "14px",
          lineHeight: "16.94px",
          letterSpacing: "0%",
          color: "#1E1E1E",
      },
      dropdownIcon: {
          width: "16px",
          height: "16px",
          transform: "rotate(90deg)",
      },
      dropdownArrow: {
          width: "5.33px",
          height: "9.33px",
          position: "absolute",
          top: "5.33px",
          left: "12.67px",
          border: "1.2px solid #1E1E1E",
          transform: "rotate(-90deg)",
      },
      
      selectOuterLayout: {
        width: "142px",
        height: "32px",
        borderRadius: "4px",
        top:"2.5px",
       // left:" 483px",
        padding: "7px 10px",
        gap: "10px",
        border: "1px solid #8888883D",
        background: "#FFFFFF",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        position: "relative",
    },

    innerLayout: {
        width: "122px",
        height: "17px",
        display: "flex",
        alignItems: "center",
        gap: "14px",
    },

    textLayout: {
        width: "92px",
        height: "17px",
        fontFamily: "Inter, sans-serif",
        fontWeight: 500,
        fontSize: "14px",
        lineHeight: "16.94px",
        letterSpacing: "0%",
        color: "#1E1E1E",
    },

    dropdownOuterLayout: {
        width: "16px",
        height: "16px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        transform: "rotate(90deg)",
        position: "absolute",
        right: "10px",
    },

    dropdownIcon: {
        width: "5.33px",
        height: "9.33px",
        position: "absolute",
        top: "5.33px",
        left: "12.67px",
        border: "1.2px solid #1E1E1E",
        transform: "rotate(-90deg)",
    },

    statusSelect: {
      width: "94px",
      height: "32px",
      borderRadius: "4px",
      padding: "7px 10px",
      top: "2.5px",
      gap: "10px",
      border: "1px solid #8888883D",
      background: "#FFFFFF",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      position: "relative",
  },

  statusText: {
      width: "44px",
      height: "17px",
      fontFamily: "Inter, sans-serif",
      fontWeight: 500,
      fontSize: "14px",
      lineHeight: "16.94px",
      letterSpacing: "0%",
      color: "#1E1E1E",
  },

  dropdownOuter: {
      width: "16px",
      height: "16px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      transform: "rotate(90deg)",
      position: "absolute",
      right: "10px",
  },

  dropdownIconStatus: {
      width: "5.33px",
      height: "9.33px",
      position: "absolute",
      top: "5.33px",
      left: "12.67px",
      // border: "1.2px solid #1E1E1E",
     // transform: "rotate(-90deg)",
     transform: "rotate(0deg)",
  },

  toggleButtonGroup: {
    width: "286px",
    height: "37px",
    borderRadius: "5px",
    padding: "5px",
    background: "#F4F4F4",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
},

toggleButton: {
    width: "69px",
    height: "27px",
    borderRadius: "5px",
    padding: "5px",
    gap: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
},

toggleButtonText: {
    fontFamily: "Inter, sans-serif",
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "14.52px",
    letterSpacing: "0%",
    textAlign: "center",
    color: "#5F5F5F",
},
  selectedButton: {
    backgroundColor: "blue",
    color: "white",
  },

  datePickerContainerStyle: {
    width: "153px",
    height: "32px",
    borderRadius: "4px",
    padding: "7px 11px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    border: "1px solid rgba(136, 136, 136, 0.24)",
    background: "#FFFFFF",
  },

  iconContainerStyle: {
    width: "14px",
    height: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  iconStyle: {
    width: "10.08px",
    height: "11.2px",
    color: "#5E8AEB",
  },

  dateTextFieldStyle: {
    width: "85px",
    height: "17px",
    fontFamily: "Inter",
    fontWeight: "500",
    fontSize: "14px",
    lineHeight: "16.94px",
    letterSpacing: "0%",
    color: "#1E1E1E",
    border: "none",
    outline: "none",
    background: "transparent",
  },

  dropdownContainerStyle: {
    width: "16px",
    height: "16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transform: "rotate(90deg)",
  },

  dropdownIconStyle: {
    width: "5.33px",
    height: "9.33px",
    transform: "rotate(-90deg)",
    borderWidth: "1.2px",
  },
  paginationContainer: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    margin: "10px 0",
    gap: "8px",
},
// pageButton: {
//   minWidth: "32px",
//   height: "32px",
//   padding: "4px",
//   fontWeight: currentPage === 1 ? "bold" : "normal",
//   border: currentPage === 1 ? "1px solid #2563EB" : "1px solid #e0e0e0",
//   borderRadius: "4px",
//   display: "flex",
//   justifyContent: "center",
//   alignItems: "center",
//   cursor: "pointer",
//   backgroundColor: currentPage === 1 ? "#EFF6FF" : "#FFFFFF",
//   color: currentPage === 1 ? "#2563EB" : "#374151",
// },
getPageButtonStyles: (currentPage) => ({
  minWidth: "32px",
  height: "32px",
  padding: "4px",
  fontWeight: currentPage === 1 ? "bold" : "normal",
  border: currentPage === 1 ? "1px solid #2563EB" : "1px solid #e0e0e0",
  borderRadius: "4px",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  cursor: "pointer",
  backgroundColor: currentPage === 1 ? "#EFF6FF" : "#FFFFFF",
  color: currentPage === 1 ? "#2563EB" : "#374151",
}),

statusChip: (status) => ({
  backgroundColor: status === "Yes" ? "#F0F9F0" : "#FEF2F2", 
  color: status === "Yes" ? "#047857" : "#B91C1C",
  border: "none",
  borderRadius: "4px",
  padding: "4px 8px",
  fontSize: "0.7rem",
  fontWeight: "bold",
}),
  };
  
  export default AdminPageTableStyles;
  
  